### ISSUE TITLE
having problems with the plugin

### ISSUE THREAD

**Issue by boxxxie** [edpaget/parinfer-mode#4]
i follow the instructions, start the server, added a simlink to the parinfer.el file. got it working with my prelude setup. 
when i enable `parinfer-mode` i get these messages whenever i edit the file i'm on.

```
Contacting host: localhost:8088
error in process sentinel: End of buffer [2 times]
```

**Comment by edpaget** [comment]
I removed the node rpc, sorry it didn't work then (and that I didn't have enough time to work on it more). If you want to give it another shot I've replaced that with the pure elisp library.
